spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password:

    hikari:
      auto-commit: true

server:
  error:
    include-stacktrace: never